In [ ]:
import pandas as pd
import numpy as np
np.random.seed(43)

In [ ]:
df = pd.DataFrame({"Name":["Mike", "Jeremy", "James"], "Age": [19, 20, 21], "Weight": [70,65, np.nan], "Gender": ["M", "M", "F"]})
print(df)
print(df.describe())

In [ ]:
df.groupby("Gender")["Age"].mean()


In [ ]:
m_agg = df[df["Gender"] == "M"].agg({"Age": "mean"}).rename("M_Age_mean")
# 2. 筛选F组，聚合weight（比如求均值）
f_agg = df[df["Gender"] == "F"].agg({"Weight": "mean"}).rename("F_weight_mean")
# 3. 合并结果
result = pd.concat([m_agg, f_agg])
print("\n聚合结果：")
print(result)

In [ ]:
df.iloc[0,1] = 20
df["Age"].unique()
df

In [28]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 6],
              [5, 7]])

In [37]:
C = A + B
D = A @ B
E = A * B
print(C,"\n", D, "\n", E)
print(np.linalg.inv(A))    # 求逆矩阵
print(np.linalg.det(A))    # 求行列式

[[ 3  8]
 [ 8 11]] 
 [[12 20]
 [26 46]] 
 [[ 2 12]
 [15 28]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [38]:
# sparse matrix稀疏矩阵
from scipy.sparse import csr_matrix